runtime: python39

env_variables:
  FLASK_ENV: "production"
  DB_USER: "gemiturn"
  DB_PASS: "your-password"
  DB_NAME: "gemiturn"
  CLOUD_SQL_CONNECTION_NAME: "your-project:your-region:your-instance"
  GEMINI_API_KEY: "your-gemini-api-key"
  JWT_SECRET_KEY: "your-jwt-secret-key"

handlers:
- url: /.*
  script: auto

entrypoint: gunicorn -b :$PORT run:app 